=== Hl4p3x/L2JMaster_2020/L2JMaster_DataPack/dist/game/data/xsd/minionData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="list">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="npc" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="minion" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:int" name="id" use="optional"/>
                      <xs:attribute type="xs:byte" name="count" use="optional"/>
                      <xs:attribute type="xs:short" name="respawnTime" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:int" name="id" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Hl4p3x/L2JMaster_2020/L2JMaster_DataPack/dist/game/data/minionData.xml
<!-- TODO : That minions need to be moved in spawn system when is done! -->
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/minionData.xsd">
	<npc id="35375"> <!-- Bloody Lord Nurka -->
		<minion id="35376" count="2" respawnTime="60" /> <!-- Partisan Healer -->
		<minion id="35377" count="8" respawnTime="60" /> <!-- Partisan Court Guard -->
		<minion id="35378" count="4" respawnTime="60" /> <!-- Partisan Court Guard -->
		<minion id="35379" count="1" respawnTime="60" /> <!-- Partisan Soldier -->
		<minion id="35380" count="2" respawnTime="60" /> <!-- Partisan Sorcerer -->
		<minion id="35381" count="2" respawnTime="60" /> <!-- Partisan Archer -->
	</npc>
	<npc id="32128"> <!-- Guardian Wizard of the Cloth -->
		<minion id="32127" count="6" respawnTime="0" /> <!-- Priest Guard -->
	</npc>
	<npc id="18353"> <!-- Guardian of Records -->
		<minion id="18349" count="1" respawnTime="0" /> <!-- Garden Guard -->
		<minion id="18350" count="1" respawnTime="0" /> <!-- Garden Guard -->
	</npc>
	<npc id="18352"> <!-- Kamael Guard -->
		<minion id="18348" count="2" respawnTime="0" /> <!-- Garden Guard -->
	</npc>
	<npc id="18356"> <!-- Harkilgamed's Gatekeeper -->
		<minion id="18348" count="1" respawnTime="0" /> <!-- Garden Guard -->
		<minion id="18351" count="1" respawnTime="0" /> <!-- Garden Guard -->
	</npc>
	<npc id="18354"> <!-- Guardian of Observation -->
		<minion id="18348" count="2" respawnTime="0" /> <!-- Garden Guard -->
	</npc>
	<npc id="18355"> <!-- Spicula's Guard -->
		<minion id="18348" count="1" respawnTime="0" /> <!-- Garden Guard -->
		<minion id="18350" count="1" respawnTime="0" /> <!-- Garden Guard -->
	</npc>
	<npc id="18360"> <!-- Katenar's Gatekeeper -->
		<minion id="18350" count="1" respawnTime="0" /> <!-- Garden Guard -->
		<minion id="18351" count="1" respawnTime="0" /> <!-- Garden Guard -->
	</npc>
	<npc id="18361"> <!-- Guardian of Prediction -->
		<minion id="18348" count="1" respawnTime="0" /> <!-- Garden Guard -->
		<minion id="18349" count="1" respawnTime="0" /> <!-- Garden Guard -->
	</npc>
	<npc id="18357"> <!-- Rodenpicula's Gatekeeper -->
		<minion id="18348" count="2" respawnTime="0" /> <!-- Garden Guard -->
	</npc>
	<npc id="18359"> <!-- Arviterre's Guardian -->
		<minion id="18349" count="2" respawnTime="0" /> <!-- Garden Guard -->
	</npc>
	<npc id="25528"> <!-- Tiberias -->
		<minion id="25529" count="1" respawnTime="60" /> <!-- Garden Guard -->
		<minion id="25530" count="3" respawnTime="60" /> <!-- Garden Guard -->
	</npc>
	<npc id="20755"> <!-- Talakin -->
		<minion id="20756" count="1" respawnTime="0" /> <!-- Talakin Archer -->
		<minion id="20757" count="1" respawnTime="0" /> <!-- Talakin Raider -->
	</npc>
	<npc id="20755"> <!-- Talakin -->
		<minion id="20756" count="1" respawnTime="0" /> <!-- Talakin Archer -->
		<minion id="20757" count="1" respawnTime="0" /> <!-- Talakin Raider -->
	</npc>
	<npc id="20755"> <!-- Talakin -->
		<minion id="20756" count="1" respawnTime="0" /> <!-- Talakin Archer -->
		<minion id="20757" count="1" respawnTime="0" /> <!-- Talakin Raider -->
	</npc>
	<npc id="20755"> <!-- Talakin -->
		<minion id="20756" count="1" respawnTime="0" /> <!-- Talakin Archer -->
		<minion id="20757" count="1" respawnTime="0" /> <!-- Talakin Raider -->
	</npc>
	<npc id="20755"> <!-- Talakin -->
		<minion id="20756" count="1" respawnTime="0" /> <!-- Talakin Archer -->
		<minion id="20757" count="1" respawnTime="0" /> <!-- Talakin Raider -->
	</npc>
	<npc id="20755"> <!-- Talakin -->
		<minion id="20756" count="1" respawnTime="0" /> <!-- Talakin Archer -->
		<minion id="20757" count="1" respawnTime="0" /> <!-- Talakin Raider -->
	</npc>
	<npc id="20755"> <!-- Talakin -->
		<minion id="20756" count="1" respawnTime="0" /> <!-- Talakin Archer -->
		<minion id="20757" count="1" respawnTime="0" /> <!-- Talakin Raider -->
	</npc>
	<npc id="20755"> <!-- Talakin -->
		<minion id="20756" count="1" respawnTime="0" /> <!-- Talakin Archer -->
		<minion id="20757" count="1" respawnTime="0" /> <!-- Talakin Raider -->
	</npc>
	<npc id="20755"> <!-- Talakin -->
		<minion id="20756" count="1" respawnTime="0" /> <!-- Talakin Archer -->
		<minion id="20757" count="1" respawnTime="0" /> <!-- Talakin Raider -->
	</npc>
	<npc id="20755"> <!-- Talakin -->
		<minion id="20756" count="1" respawnTime="0" /> <!-- Talakin Archer -->
		<minion id="20757" count="1" respawnTime="0" /> <!-- Talakin Raider -->
	</npc>
	<npc id="20755"> <!-- Talakin -->
		<minion id="20756" count="1" respawnTime="0" /> <!-- Talakin Archer -->
		<minion id="20757" count="1" respawnTime="0" /> <!-- Talakin Raider -->
	</npc>
	<npc id="20755"> <!-- Talakin -->
		<minion id="20756" count="1" respawnTime="0" /> <!-- Talakin Archer -->
		<minion id="20757" count="1" respawnTime="0" /> <!-- Talakin Raider -->
	</npc>
	<npc id="20755"> <!-- Talakin -->
		<minion id="20756" count="1" respawnTime="0" /> <!-- Talakin Archer -->
		<minion id="20757" count="1" respawnTime="0" /> <!-- Talakin Raider -->
	</npc>
	<npc id="20755"> <!-- Talakin -->
		<minion id="20756" count="1" respawnTime="0" /> <!-- Talakin Archer -->
		<minion id="20757" count="1" respawnTime="0" /> <!-- Talakin Raider -->
	</npc>
	<npc id="20755"> <!-- Talakin -->
		<minion id="20756" count="1" respawnTime="0" /> <!-- Talakin Archer -->
		<minion id="20757" count="1" respawnTime="0" /> <!-- Talakin Raider -->
	</npc>
	<npc id="20755"> <!-- Talakin -->
		<minion id="20756" count="1" respawnTime="0" /> <!-- Talakin Archer -->
		<minion id="20757" count="1" respawnTime="0" /> <!-- Talakin Raider -->
	</npc>
	<npc id="20755"> <!-- Talakin -->
		<minion id="20756" count="1" respawnTime="0" /> <!-- Talakin Archer -->
		<minion id="20757" count="1" respawnTime="0" /> <!-- Talakin Raider -->
	</npc>
	<npc id="20939"> <!-- Tanor Silenos Warrior -->
		<minion id="20936" count="1" respawnTime="0" /> <!-- Tanor Silenos -->
		<minion id="20937" count="1" respawnTime="0" /> <!-- Tanor Silenos Grunt -->
		<minion id="20938" count="1" respawnTime="0" /> <!-- Tanor Silenos Scout -->
	</npc>
	<npc id="20939"> <!-- Tanor Silenos Warrior -->
		<minion id="20936" count="1" respawnTime="0" /> <!-- Tanor Silenos -->
		<minion id="20937" count="1" respawnTime="0" /> <!-- Tanor Silenos Grunt -->
		<minion id="20938" count="1" respawnTime="0" /> <!-- Tanor Silenos Scout -->
	</npc>
	<npc id="20944"> <!-- Nightmare Lord -->
		<minion id="20942" count="1" respawnTime="0" /> <!-- Nightmare Guide -->
		<minion id="20943" count="2" respawnTime="0" /> <!-- Nightmare Keeper -->
	</npc>
	<npc id="20939"> <!-- Tanor Silenos Warrior -->
		<minion id="20936" count="1" respawnTime="0" /> <!-- Tanor Silenos -->
		<minion id="20937" count="1" respawnTime="0" /> <!-- Tanor Silenos Grunt -->
		<minion id="20938" count="1" respawnTime="0" /> <!-- Tanor Silenos Scout -->
	</npc>
	<npc id="20944"> <!-- Nightmare Lord -->
		<minion id="20942" count="1" respawnTime="0" /> <!-- Nightmare Guide -->
		<minion id="20943" count="2" respawnTime="0" /> <!-- Nightmare Keeper -->
	</npc>
	<npc id="20939"> <!-- Tanor Silenos Warrior -->
		<minion id="20936" count="1" respawnTime="0" /> <!-- Tanor Silenos -->
		<minion id="20937" count="1" respawnTime="0" /> <!-- Tanor Silenos Grunt -->
		<minion id="20938" count="1" respawnTime="0" /> <!-- Tanor Silenos Scout -->
	</npc>
	<npc id="20944"> <!-- Nightmare Lord -->
		<minion id="20942" count="1" respawnTime="0" /> <!-- Nightmare Guide -->
		<minion id="20943" count="2" respawnTime="0" /> <!-- Nightmare Keeper -->
	</npc>
	<npc id="20941"> <!-- Tanor Silenos Chieftain -->
		<minion id="20940" count="3" respawnTime="0" /> <!-- Tanor Silenos Shaman -->
	</npc>
	<npc id="20939"> <!-- Tanor Silenos Warrior -->
		<minion id="20936" count="1" respawnTime="0" /> <!-- Tanor Silenos -->
		<minion id="20937" count="1" respawnTime="0" /> <!-- Tanor Silenos Grunt -->
		<minion id="20938" count="1" respawnTime="0" /> <!-- Tanor Silenos Scout -->
	</npc>
	<npc id="20944"> <!-- Nightmare Lord -->
		<minion id="20942" count="1" respawnTime="0" /> <!-- Nightmare Guide -->
		<minion id="20943" count="2" respawnTime="0" /> <!-- Nightmare Keeper -->
	</npc>
	<npc id="20941"> <!-- Tanor Silenos Chieftain -->
		<minion id="20940" count="3" respawnTime="0" /> <!-- Tanor Silenos Shaman -->
	</npc>
	<npc id="20939"> <!-- Tanor Silenos Warrior -->
		<minion id="20936" count="1" respawnTime="0" /> <!-- Tanor Silenos -->
		<minion id="20937" count="1" respawnTime="0" /> <!-- Tanor Silenos Grunt -->
		<minion id="20938" count="1" respawnTime="0" /> <!-- Tanor Silenos Scout -->
	</npc>
	<npc id="20944"> <!-- Nightmare Lord -->
		<minion id="20942" count="1" respawnTime="0" /> <!-- Nightmare Guide -->
		<minion id="20943" count="2" respawnTime="0" /> <!-- Nightmare Keeper -->
	</npc>
	<npc id="20939"> <!-- Tanor Silenos Warrior -->
		<minion id="20936" count="1" respawnTime="0" /> <!-- Tanor Silenos -->
		<minion id="20937" count="1" respawnTime="0" /> <!-- Tanor Silenos Grunt -->
		<minion id="20938" count="1" respawnTime="0" /> <!-- Tanor Silenos Scout -->
	</npc>
	<npc id="20944"> <!-- Nightmare Lord -->
		<minion id="20942" count="1" respawnTime="0" /> <!-- Nightmare Guide -->
		<minion id="20943" count="2" respawnTime="0" /> <!-- Nightmare Keeper -->
	</npc>
	<npc id="20941"> <!-- Tanor Silenos Chieftain -->
		<minion id="20940" count="3" respawnTime="0" /> <!-- Tanor Silenos Shaman -->
	</npc>
	<npc id="20939"> <!-- Tanor Silenos Warrior -->
		<minion id="20936" count="1" respawnTime="0" /> <!-- Tanor Silenos -->
		<minion id="20937" count="1" respawnTime="0" /> <!-- Tanor Silenos Grunt -->
		<minion id="20938" count="1" respawnTime="0" /> <!-- Tanor Silenos Scout -->
	</npc>
	<npc id="20939"> <!-- Tanor Silenos Warrior -->
		<minion id="20936" count="1" respawnTime="0" /> <!-- Tanor Silenos -->
		<minion id="20937" count="1" respawnTime="0" /> <!-- Tanor Silenos Grunt -->
