=== Hl4p3x/L2JMaster_2020/L2JMaster_DataPack/dist/game/data/xsd/npcs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="npc" type="npcType" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="npcType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="acquire" type="acquireType" minOccurs="0" maxOccurs="1" />
			<xs:element name="ai" type="aiType" minOccurs="0" maxOccurs="1" />
			<xs:element name="collision" type="collisionType" minOccurs="0" maxOccurs="1" />
			<xs:element name="corpseTime" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="1" />
			<xs:element name="dropLists" type="dropListsType" minOccurs="0" maxOccurs="1" />
			<xs:element name="equipment" type="equipmentType" minOccurs="0" maxOccurs="1" />
			<xs:element name="exCrtEffect" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="parameters" type="parametersType" minOccurs="0" maxOccurs="1" />
			<xs:element name="race" type="xs:token" minOccurs="0" maxOccurs="1" />
			<xs:element name="sNpcPropHpRate" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="sex" type="xs:token" minOccurs="0" maxOccurs="1" />
			<xs:element name="shots" type="shotsType" minOccurs="0" maxOccurs="1" />
			<xs:element name="skillList" type="skillType" minOccurs="0" maxOccurs="1" />
			<xs:element name="stats" type="statsType" minOccurs="0" maxOccurs="1" />
			<xs:element name="status" type="statusType" minOccurs="0" maxOccurs="1" />
		</xs:choice>
		<xs:attribute name="id" type="xs:positiveInteger" use="required" />
		<xs:attribute name="displayId" type="xs:positiveInteger" />
		<xs:attribute name="level" type="xs:byte" />
		<xs:attribute name="type" type="xs:token" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="usingServerSideName" type="xs:boolean" />
		<xs:attribute name="title" type="xs:string" />
		<xs:attribute name="usingServerSideTitle" type="xs:boolean" />
	</xs:complexType>
	
	<xs:complexType name="acquireType">
		<xs:attribute name="expRate" type="xs:decimal" />
		<xs:attribute name="sp" type="xs:decimal" />
		<xs:attribute name="raidPoints" type="xs:decimal" />
	</xs:complexType>
	
	<xs:complexType name="aiType">
		<xs:all>
			<xs:element name="skill" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="minChance" type="xs:nonNegativeInteger" />
					<xs:attribute name="maxChance" type="xs:nonNegativeInteger" />
					<xs:attribute name="primaryId" type="xs:nonNegativeInteger" />
					<xs:attribute name="shortRangeId" type="xs:nonNegativeInteger" />
					<xs:attribute name="shortRangeChance" type="xs:nonNegativeInteger" />
					<xs:attribute name="longRangeId" type="xs:nonNegativeInteger" />
					<xs:attribute name="longRangeChance" type="xs:nonNegativeInteger" />
				</xs:complexType>
			</xs:element>
			<xs:element name="clanList" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:choice minOccurs="1" maxOccurs="unbounded">
						<xs:element name="clan" type="xs:token" />
						<xs:element name="ignoreNpcId" type="xs:nonNegativeInteger" />
					</xs:choice>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="type" type="xs:token" />
		<xs:attribute name="aggroRange" type="xs:nonNegativeInteger" />
		<xs:attribute name="clanHelpRange" type="xs:nonNegativeInteger" />
		<xs:attribute name="dodge" type="xs:nonNegativeInteger" />
		<xs:attribute name="isChaos" type="xs:boolean" />
		<xs:attribute name="isAggressive" type="xs:boolean" />
	</xs:complexType>
	
	<xs:complexType name="collisionType">
		<xs:all>
			<xs:element name="radius" type="size" minOccurs="0" maxOccurs="1" />
			<xs:element name="height" type="size" minOccurs="0" maxOccurs="1" />
		</xs:all>
	</xs:complexType>
	
	<xs:complexType name="size">
		<xs:attribute name="normal" type="xs:decimal" />
		<xs:attribute name="grown" type="xs:decimal" />
	</xs:complexType>
	
		<xs:complexType name="dropListsType">
		<xs:all>
			<xs:element name="death" type="dropList" minOccurs="0" maxOccurs="1" />
			<xs:element name="corpse" type="dropList" minOccurs="0" maxOccurs="1" />
		</xs:all>
	</xs:complexType>
	
	<xs:complexType name="dropList">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="item" type="dropListItem" />
			<xs:element name="group">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="item" type="dropListItem" minOccurs="1" maxOccurs="unbounded" />
					</xs:sequence>
					<xs:attribute name="chance" type="xs:decimal" />
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="dropListItem">
		<xs:attribute name="id" type="xs:positiveInteger" use="required" />
		<xs:attribute name="min" type="xs:nonNegativeInteger" />
		<xs:attribute name="max" type="xs:positiveInteger" />
		<xs:attribute name="chance" type="xs:decimal" />
	</xs:complexType>
	
	<xs:complexType name="equipmentType">
		<xs:attribute name="chest" type="xs:nonNegativeInteger" />
		<xs:attribute name="rhand" type="xs:nonNegativeInteger" />
		<xs:attribute name="lhand" type="xs:nonNegativeInteger" />
		<xs:attribute name="weaponEnchant" type="xs:nonNegativeInteger" />
	</xs:complexType>
	
	<xs:complexType name="parametersType">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="param">
				<xs:complexType>
					<xs:attribute name="name" type="xs:token" use="required" />
					<xs:attribute name="value" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
			<xs:element name="skill">
				<xs:complexType>
					<xs:attribute name="name" type="xs:token" use="required" />
					<xs:attribute name="id" type="xs:positiveInteger" use="required" />
					<xs:attribute name="level" type="xs:positiveInteger" use="required" />
				</xs:complexType>
			</xs:element>
			<xs:element name="minions">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="npc" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="id" type="xs:positiveInteger" use="required" />
								<xs:attribute name="count" type="xs:positiveInteger" use="required" />
								<xs:attribute name="respawnTime" type="xs:nonNegativeInteger" use="required" />
								<xs:attribute name="weightPoint" type="xs:integer" use="required" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="name" type="xs:token" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="shotsType">
		<xs:attribute name="soul" type="xs:nonNegativeInteger" />
		<xs:attribute name="spirit" type="xs:nonNegativeInteger" />
		<xs:attribute name="shotChance" type="xs:nonNegativeInteger" />
		<xs:attribute name="spiritChance" type="xs:nonNegativeInteger" />
	</xs:complexType>

	<xs:complexType name="skillType">
		<xs:sequence>
			<xs:element name="skill" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="id" type="xs:nonNegativeInteger" use="required" />
					<xs:attribute name="level" type="xs:nonNegativeInteger" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="statsType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="vitals" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="hp" type="xs:decimal" />
					<xs:attribute name="hpRegen" type="xs:decimal" />
					<xs:attribute name="mp" type="xs:decimal" />
					<xs:attribute name="mpRegen" type="xs:decimal" />
				</xs:complexType>
			</xs:element>
			<xs:element name="attack" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="physical" type="xs:decimal" />
					<xs:attribute name="magical" type="xs:decimal" />
					<xs:attribute name="random" type="xs:nonNegativeInteger" />
					<xs:attribute name="critical" type="xs:nonNegativeInteger" />
					<xs:attribute name="accuracy" type="xs:decimal" />
					<xs:attribute name="attackSpeed" type="xs:nonNegativeInteger" />
					<xs:attribute name="reuseDelay" type="xs:nonNegativeInteger" />
					<xs:attribute name="type">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="SWORD" />
								<xs:enumeration value="BLUNT" />
								<xs:enumeration value="DAGGER" />
								<xs:enumeration value="BOW" />
								<xs:enumeration value="DUAL" />
								<xs:enumeration value="POLE" />
								<xs:enumeration value="DUALFIST" />
								<xs:enumeration value="FIST" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="range" type="xs:nonNegativeInteger" />
					<xs:attribute name="distance" type="xs:nonNegativeInteger" />
					<xs:attribute name="width" type="xs:nonNegativeInteger" />
				</xs:complexType>
			</xs:element>
			<xs:element name="defence" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="physical" type="xs:decimal" />
					<xs:attribute name="magical" type="xs:decimal" />
					<xs:attribute name="evasion" type="xs:integer" />
					<xs:attribute name="shield" type="xs:nonNegativeInteger" />
					<xs:attribute name="shieldRate" type="xs:nonNegativeInteger" />
				</xs:complexType>
			</xs:element>
			<xs:element name="attribute" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:all>
						<xs:element name="attack" minOccurs="0" maxOccurs="1">
							<xs:complexType>
								<xs:attribute name="type">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="FIRE" />
											<xs:enumeration value="WATER" />
											<xs:enumeration value="WIND" />
											<xs:enumeration value="EARTH" />
											<xs:enumeration value="DARK" />
											<xs:enumeration value="HOLY" />
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="value" type="xs:nonNegativeInteger" />
							</xs:complexType>
						</xs:element>
						<xs:element name="defence" minOccurs="0" maxOccurs="1">
							<xs:complexType>
								<xs:attribute name="fire" type="xs:integer" />
								<xs:attribute name="water" type="xs:integer" />
								<xs:attribute name="wind" type="xs:integer" />
								<xs:attribute name="earth" type="xs:integer" />
								<xs:attribute name="holy" type="xs:integer" />
								<xs:attribute name="dark" type="xs:integer" />
								<xs:attribute name="default" type="xs:integer" />
							</xs:complexType>
						</xs:element>
					</xs:all>
				</xs:complexType>
			</xs:element>
			<xs:element name="speed" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:all>
						<xs:element name="walk" minOccurs="0" maxOccurs="1">
							<xs:complexType>
								<xs:attribute name="ground" type="xs:decimal" />
								<xs:attribute name="swim" type="xs:decimal" />
								<xs:attribute name="fly" type="xs:decimal" />
							</xs:complexType>
						</xs:element>
						<xs:element name="run" minOccurs="0" maxOccurs="1">
							<xs:complexType>
								<xs:attribute name="ground" type="xs:decimal" />
								<xs:attribute name="swim" type="xs:decimal" />
								<xs:attribute name="fly" type="xs:decimal" />
							</xs:complexType>
						</xs:element>
					</xs:all>
				</xs:complexType>
			</xs:element>
			<xs:element name="hitTime" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="1" />
		</xs:choice>
		<xs:attribute name="str" type="xs:nonNegativeInteger" />
		<xs:attribute name="int" type="xs:nonNegativeInteger" />
		<xs:attribute name="dex" type="xs:nonNegativeInteger" />
		<xs:attribute name="wit" type="xs:nonNegativeInteger" />
		<xs:attribute name="con" type="xs:nonNegativeInteger" />
		<xs:attribute name="men" type="xs:nonNegativeInteger" />
	</xs:complexType>
	
	<xs:complexType name="statusType">
		<xs:attribute name="unique" type="xs:boolean" />
		<xs:attribute name="attackable" type="xs:boolean" />
		<xs:attribute name="targetable" type="xs:boolean" />
		<xs:attribute name="undying" type="xs:boolean" />
		<xs:attribute name="showName" type="xs:boolean" />
		<xs:attribute name="flying" type="xs:boolean" />
		<xs:attribute name="canMove" type="xs:boolean" />
		<xs:attribute name="noSleepMode" type="xs:boolean" />
		<xs:attribute name="passableDoor" type="xs:boolean" />
		<xs:attribute name="hasSummoner" type="xs:boolean" />
		<xs:attribute name="canBeSown" type="xs:boolean" />
	</xs:complexType>
</xs:schema>

=== Hl4p3x/L2JMaster_2020/L2JMaster_DataPack/dist/game/data/stats/npcs/custom/custom.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/npcs.xsd">
	<npc id="50007" displayId="31324" name="Andromeda" usingServerSideName="true" title="Wedding Manager" usingServerSideTitle="true" type="L2Npc">
		<collision>
			<radius normal="8" />
			<height normal="23" />
		</collision>
	</npc>
	<npc id="70010" displayId="31606" name="Catrina" usingServerSideName="true" title="TvT Event Manager" usingServerSideTitle="true" type="L2Npc">
		<collision>
			<radius normal="8" />
			<height normal="15" />
		</collision>
	</npc>
	<npc id="900100" displayId="20432" level="1" name="Elpy" type="L2EventMonster">
		<stats str="40" int="21" dex="30" wit="20" con="43" men="20">
			<vitals hp="40" hpRegen="3" mp="36" mpRegen="1" />
			<attack physical="8" magical="7" />
			<defence physical="25" magical="40" />
		</stats>
		<status undying="false" />
		<collision>
			<radius normal="5" />
			<height normal="4.5" />
		</collision>
	</npc>
	<npc id="900101" displayId="32365" name="Snowden" usingServerSideName="true" title="Event Manager">
		<collision>
			<radius normal="5" />
			<height normal="12.5" />
		</collision>
	</npc>
	<npc id="900102" displayId="13098" level="80" name="Event Treasure Chest" type="L2Monster">
		<stats str="40" int="21" dex="30" wit="20" con="43" men="20">
			<vitals hp="2880" mp="1524" />
			<defence physical="1499" magical="1035.28" />
		</stats>
		<collision>
			<radius normal="8.5" />
			<height normal="8.5" />
		</collision>
	</npc>
	<npc id="900103" displayId="32365" name="Start" usingServerSideName="true" title="Event Manager">
		<collision>
			<radius normal="5" />
			<height normal="12.5" />
		</collision>
	</npc>
	<npc id="900104" displayId="32365" name="Finish" usingServerSideName="true" title="Event Manager">
		<collision>
			<radius normal="5" />
			<height normal="12.5" />
		</collision>
	</npc>
	<npc id="1000003" displayId="32226" name="Shiela" usingServerSideName="true" title="L2J NPC Buffer" usingServerSideTitle="true" type="L2NpcBuffer">
		<collision>
			<radius normal="11" />
			<height normal="22.25" />
		</collision>
	</npc>
		<npc id="36600" displayId="30026" name="Ermak" usingServerSideName="true" title="EventEngine" usingServerSideTitle="true" type="L2Npc">
		<collision>
			<radius normal="8" />
			<height normal="23.5" />
		</collision>
	</npc>
	<npc id="36601" displayId="35062" name="Flag" usingServerSideName="true" title="" usingServerSideTitle="false" type="L2Npc">
		<collision>
			<radius normal="11" />
			<height normal="22.25" />
		</collision>
	</npc>
	<npc id="36603" displayId="32027" name="Holder" usingServerSideName="true" title="" usingServerSideTitle="false" type="L2Npc">
		<collision>
			<radius normal="11" />
			<height normal="22.25" />
		</collision>
	</npc>	
	<npc id="37616" displayId="32736" name="Medal Shop" usingServerSideName="true" title="L2JMaster.org" usingServerSideTitle="true" type="L2Merchant">
		<collision>
			<radius normal="10" />
			<height normal="22" />
		</collision>
	</npc>
	<npc id="37617" displayId="32586" name="Donate Shop" usingServerSideName="true" title="L2JMaster.org" usingServerSideTitle="true" type="L2Merchant">
		<collision>
			<radius normal="15" />
			<height normal="24" />
		</collision>
	</npc>
	<npc id="37618" displayId="32587" name="Vote Shop" usingServerSideName="true" title="L2JMaster.org" usingServerSideTitle="true" type="L2Merchant">
		<collision>
			<radius normal="15" />
			<height normal="24" />
		</collision>
	</npc>	
	<npc id="37619" displayId="32733" name="Forgotten Shop" usingServerSideName="true" title="L2JMaster.org" usingServerSideTitle="true" type="L2Merchant">
		<collision>
			<radius normal="15" />
			<height normal="27.5" />
		</collision>
	</npc>
	<npc id="37620" displayId="32237" name="Aden" usingServerSideName="true" title="Cloak Manager" usingServerSideTitle="true" type="L2Merchant">
		<collision>
			<radius normal="9" />
			<height normal="23" />
		</collision>
	</npc>
	<npc id="37621" displayId="32237" name="Dion" usingServerSideName="true" title="Cloak Manager" usingServerSideTitle="true" type="L2Merchant">
		<collision>
			<radius normal="9" />
			<height normal="23" />
		</collision>
	</npc>
	<npc id="37622" displayId="32237" name="Giran" usingServerSideName="true" title="Cloak Manager" usingServerSideTitle="true" type="L2Merchant">
		<collision>
			<radius normal="9" />
			<height normal="23" />
		</collision>
	</npc>
	<npc id="37623" displayId="32237" name="Gludio" usingServerSideName="true" title="Cloak Manager" usingServerSideTitle="true" type="L2Merchant">
		<collision>
			<radius normal="9" />
			<height normal="23" />
		</collision>
	</npc>
	<npc id="37624" displayId="32237" name="Goddard" usingServerSideName="true" title="Cloak Manager" usingServerSideTitle="true" type="L2Merchant">
		<collision>
			<radius normal="9" />
			<height normal="23" />
		</collision>
	</npc>
	<npc id="37625" displayId="32237" name="Innadril" usingServerSideName="true" title="Cloak Manager" usingServerSideTitle="true" type="L2Merchant">
		<collision>
			<radius normal="9" />
			<height normal="23" />
		</collision>
	</npc>
	<npc id="37626" displayId="32237" name="Oren" usingServerSideName="true" title="Cloak Manager" usingServerSideTitle="true" type="L2Merchant">
		<collision>
			<radius normal="9" />
			<height normal="23" />
		</collision>
	</npc>
	<npc id="37627" displayId="32237" name="Rune" usingServerSideName="true" title="Cloak Manager" usingServerSideTitle="true" type="L2Merchant">
		<collision>
			<radius normal="9" />
			<height normal="23" />
		</collision>
	</npc>
	<npc id="37628" displayId="32237" name="Schuttgart" usingServerSideName="true" title="Cloak Manager" usingServerSideTitle="true" type="L2Merchant">
		<collision>
			<radius normal="9" />
			<height normal="23" />
		</collision>
	</npc>
	<npc id="37629" displayId="1565" name="Casino" usingServerSideName="true" title="L2JMaster.org" usingServerSideTitle="true" type="L2Merchant">
		<collision>
			<radius normal="14.5" />
			<height normal="17.5" />
		</collision>
	</npc>	
	<npc id="37632" displayId="1564" name="Top PvP Pk" usingServerSideName="true" title="L2JMaster.org" usingServerSideTitle="true" type="L2Merchant">
		<collision>
			<radius normal="13.2" />
			<height normal="16.9" />
		</collision>
	</npc>	
	<npc id="36630" displayId="32548" name="Bug Report" usingServerSideName="true" title="L2JMaster.org" usingServerSideTitle="true" type="L2Npc">
		<collision>
			<radius normal="12.5" />
			<height normal="25" />
		</collision>
	</npc>	
	<npc id="36631" displayId="13298" name="Services" usingServerSideName="true" title="L2JMaster.org" usingServerSideTitle="true" type="L2Npc">
		<collision>
			<radius normal="11" />
			<height normal="23" />
		</collision>
	</npc>
	<npc id="502" displayId="103" name="Christmas" usingServerSideName="true" title="L2JMaster.org" usingServerSideTitle="true" type="L2Npc">
		<collision>
			<radius normal="8" />
			<height normal="24" />
		</collision>
	</npc>	
	<npc id="504" displayId="125" name="Halloween" usingServerSideName="true" title="L2JMaster.org" usingServerSideTitle="true" type="L2Npc">
		<collision>
			<radius normal="11" />
			<height normal="23" />
		</collision>
	</npc>	
	<npc id="505" displayId="13135" name="Scarecrow" usingServerSideName="true" title="Halloween Ghost" usingServerSideTitle="true" type="L2Monster">
		<stats str="40" int="21" dex="30" wit="20" con="43" men="20">
			<vitals hp="2880" mp="1524" />
			<defence physical="1499" magical="1035.28" />
		</stats>
		<collision>
			<radius normal="13" />
			<height normal="30" />
		</collision>
	</npc>	
	<npc id="506" displayId="25613" name="Element Energy" usingServerSideName="true" title="TAE Manager" usingServerSideTitle="true" type="L2Npc">
		<collision>
			<radius normal="8.5" />
			<height normal="25" />
		</collision>
	</npc>	
	<npc id="9999" displayId="30135" name="Buffer" usingServerSideName="true" title="L2JMaster.org" usingServerSideTitle="true" type="L2NpcBuffer">
		<collision>
			<radius normal="8.00" />
			<height normal="24.00" />
		</collision>
	</npc>
	<npc id="9997" displayId="30148" name="VIP Buffer" usingServerSideName="true" title="L2JMaster.org" usingServerSideTitle="true" type="L2NpcBuffer">
		<collision>
			<radius normal="8.00" />
			<height normal="24.00" />
		</collision>
	</npc>
	<npc id="958" displayId="30110" name="Global Gk" usingServerSideName="true" title="L2JMaster.org" usingServerSideTitle="true" type="L2Teleporter">
		<collision>
			<radius normal="11" />
			<height normal="22.25" />
		</collision>
	</npc>
	<npc id="1010" displayId="30110" name="Delevel" usingServerSideName="true" title="L2JMaster.org" usingServerSideTitle="true" type="L2Npc">
		<collision>
			<radius normal="11" />
			<height normal="22.25" />
		</collision>
	</npc>
	<npc id="1011" displayId="30110" name="UpLevel" usingServerSideName="true" title="L2JMaster.org" usingServerSideTitle="true" type="L2Npc">
		<collision>
			<radius normal="11" />
			<height normal="22.25" />
		</collision>
	</npc>
	<npc id="9994" displayId="135" name="Enchant" usingServerSideName="true" title="L2JMaster.org" usingServerSideTitle="true" type="L2Npc">
		<collision>
			<radius normal="11" />
			<height normal="22.25" />
		</collision>
	</npc>
	<npc id="1012" displayId="1565" name="Achievement" usingServerSideName="true" title="L2JMaster.org" usingServerSideTitle="true" type="L2Npc">
		<collision>
			<radius normal="14.5" />
			<height normal="17.5" />
		</collision>
	</npc>
	<npc id="10002" displayId="1565" name="GM Shop" usingServerSideName="true" title="L2JMaster.org" usingServerSideTitle="true" type="L2Merchant">
		<collision>
			<radius normal="14.5" />
			<height normal="17.5" />
		</collision>
	</npc>	
</list>

=== Hl4p3x/L2JMaster_2020/L2JMaster_DataPack/dist/game/data/stats/npcs/25800-25899.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/npcs.xsd">
	<npc id="25800" level="25" type="L2RaidBoss" name="Mammon Collector Talos" title="Lord of Destruction">
		<!-- Confirmed H5 -->
		<parameters>
			<minions name="Privates">
				<npc id="25801" count="3" respawnTime="360" weightPoint="1" /> <!-- Talos' Cohort -->
			</minions>
			<param name="RaidSpawnMusic" value="Rm01_A" />
			<skill name="RangeHold_a" id="4197" level="2" /> <!-- Hold -->
		</parameters>
		<race>DEMONIC</race>
		<sex>MALE</sex>
		<acquire expRate="4065.61996889739" sp="95136" raidPoints="320" />
		<stats str="60" int="76" dex="73" wit="70" con="57" men="80">
			<vitals hp="43316.3085364372" hpRegen="18.4385313667577" mp="259.2" mpRegen="1.5" />
			<attack physical="74.2223188804512" magical="4.67967242276365" random="10" critical="4" accuracy="4.75" attackSpeed="253" type="FIST" range="40" distance="80" width="120" />
			<defence physical="305.50599" magical="149.04" />
			<attribute>
				<defence fire="20" water="20" wind="20" earth="20" holy="-13" dark="53" />
			</attribute>
			<speed>
				<walk ground="41" />
				<run ground="190" />
			</speed>
		</stats>
		<skillList>
			<skill id="4045" level="1" /> <!-- Resist Full Magic Attack -->
			<skill id="4197" level="2" /> <!-- Hold -->
			<skill id="4273" level="3" /> <!-- Resist Daggers/Rapier Weapon -->
			<skill id="4274" level="1" /> <!-- Blunt Weapon Weak Point -->
			<skill id="4408" level="1" /> <!-- HP Increase (1x) -->
			<skill id="4409" level="1" /> <!-- MP Increase (1x) -->
			<skill id="4410" level="11" /> <!-- Average P. Atk. -->
			<skill id="4411" level="11" /> <!-- Average M. Atk. -->
			<skill id="4412" level="11" /> <!-- Average P. Def. -->
			<skill id="4413" level="11" /> <!-- Average M. Def. -->
			<skill id="4414" level="2" /> <!-- Standard Type -->
			<skill id="4415" level="1" /> <!-- Bare Hands -->
			<skill id="4416" level="9" /> <!-- Demons -->
			<skill id="4444" level="2" /> <!-- Higher Resist Bow/Crossbow Weapons -->
			<skill id="4494" level="1" /> <!-- Raid Boss -->
			<skill id="4983" level="1" /> <!-- Raid Boss - Level 25 -->
		</skillList>
		<exCrtEffect>true</exCrtEffect>
		<ai type="BALANCED" clanHelpRange="300" />
		<dropLists>
			<death>
				<group chance="73.1441">
					<item id="393" min="1" max="1" chance="17.1639" /> <!-- Mithril Banded Mail -->
					<item id="394" min="1" max="1" chance="17.1639" /> <!-- Reinforced Leather Shirt -->
					<item id="415" min="1" max="1" chance="27.4341" /> <!-- Mithril Banded Gaiters -->
					<item id="416" min="1" max="1" chance="27.4341" /> <!-- Reinforced Leather Gaiters -->
					<item id="223" min="1" max="1" chance="17.1639" /> <!-- Kukuri -->
					<item id="238" min="1" max="1" chance="2.701" /> <!-- Dagger of Mana -->
					<item id="239" min="1" max="1" chance="2.701" /> <!-- Mystic Knife -->
					<item id="241" min="1" max="1" chance="2.701" /> <!-- Shilen Knife -->
				</group>
				<group chance="68.9993">
					<item id="1938" min="60" max="180" chance="23.8522" /> <!-- Mithril Banded Mail Material -->
					<item id="1939" min="28" max="84" chance="66.7799" /> <!-- Mithril Banded Gaiters Material -->
					<item id="2028" min="27" max="81" chance="9.3679" /> <!-- Shilen Knife Edge -->
				</group>
				<group chance="1.2886">
					<item id="22229" min="1" max="1" chance="100" /> <!-- Scroll: Enchant Weapon of Destruction (D-Grade) - Event -->
				</group>
			</death>
		</dropLists>
		<collision>
			<radius normal="13" />
			<height normal="37.5" />
		</collision>
	</npc>
	<npc id="25801" level="22" type="L2Monster" name="Talos' Cohort" title="Follower of Destruction">
		<!-- Confirmed H5 -->
		<parameters>
			<skill name="PhysicalSpecial_a" id="4743" level="2" /> <!-- BOSS Strike -->
		</parameters>
		<race>DEMONIC</race>
		<sex>MALE</sex>
		<stats str="40" int="21" dex="30" wit="20" con="43" men="20">
			<vitals hp="6247.18478795455" hpRegen="17.1576881427546" mp="218.52" mpRegen="1.5" />
			<attack physical="231.186222377034" magical="58.1778709153521" random="10" critical="4" accuracy="4.75" attackSpeed="253" type="FIST" range="40" distance="80" width="120" />
			<defence physical="138.98541" magical="135.6" />
			<attribute>
				<defence fire="20" water="20" wind="20" earth="20" holy="-13" dark="53" />
			</attribute>
			<speed>
				<walk ground="80" />
				<run ground="190" />
			</speed>
			<hitTime>350</hitTime>
		</stats>
		<skillList>
			<skill id="4045" level="1" /> <!-- Resist Full Magic Attack -->
			<skill id="4273" level="3" /> <!-- Resist Daggers/Rapier Weapon -->
			<skill id="4274" level="1" /> <!-- Blunt Weapon Weak Point -->
			<skill id="4408" level="1" /> <!-- HP Increase (1x) -->
			<skill id="4409" level="1" /> <!-- MP Increase (1x) -->
			<skill id="4410" level="11" /> <!-- Average P. Atk. -->
			<skill id="4411" level="11" /> <!-- Average M. Atk. -->
			<skill id="4412" level="11" /> <!-- Average P. Def. -->
			<skill id="4413" level="11" /> <!-- Average M. Def. -->
			<skill id="4414" level="3" /> <!-- Light Armor Type -->
			<skill id="4415" level="1" /> <!-- Bare Hands -->
			<skill id="4416" level="9" /> <!-- Demons -->
			<skill id="4444" level="2" /> <!-- Higher Resist Bow/Crossbow Weapons -->
			<skill id="4743" level="2" /> <!-- BOSS Strike -->
		</skillList>
		<exCrtEffect>true</exCrtEffect>
		<ai clanHelpRange="300" />
		<collision>
			<radius normal="14" />
			<height normal="36" />
		</collision>
	</npc>
</list>
